services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: "fastapi dev app/main.py --proxy-headers --host 0.0.0.0 --port 80"
    volumes:
      - .:/code/app
    env_file:
      - .env
    ports:
      - 8001:80
    restart: always
